/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'userId' : IDL.Text,
  'goals' : IDL.Text,
  'gender' : IDL.Text,
  'healthConditions' : IDL.Vec(IDL.Text),
  'dietType' : IDL.Text,
});
export const AggregateAnalytics = IDL.Record({
  'activeUsers' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'nutrientTrends' : IDL.Text,
  'averageMoodScore' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FoodEntry = IDL.Record({
  'id' : IDL.Text,
  'calories' : IDL.Float64,
  'time' : Timestamp,
  'omega3' : IDL.Float64,
  'magnesium' : IDL.Float64,
  'image' : IDL.Opt(ExternalBlob),
  'foodName' : IDL.Text,
});
export const MoodEntry = IDL.Record({
  'id' : IDL.Text,
  'time' : Timestamp,
  'score' : IDL.Float64,
  'moodTags' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'restricted' : IDL.Null,
  'suspended' : IDL.Null,
});
export const GetFoodEntriesFrom = IDL.Record({
  'foodNames' : IDL.Vec(IDL.Text),
  'skip' : IDL.Nat,
  'timeRange' : IDL.Variant({
    'all' : IDL.Null,
    'entriesBefore' : Timestamp,
    'entriesAfter' : Timestamp,
    'entriesBetween' : IDL.Tuple(Timestamp, Timestamp),
  }),
  'fromUser' : IDL.Principal,
  'entriesToGet' : IDL.Nat,
});
export const GetFoodEntriesRequest = IDL.Record({
  'foodNames' : IDL.Vec(IDL.Text),
  'skip' : IDL.Nat,
  'timeRange' : IDL.Variant({
    'all' : IDL.Null,
    'entriesBefore' : Timestamp,
    'entriesAfter' : Timestamp,
    'entriesBetween' : IDL.Tuple(Timestamp, Timestamp),
  }),
  'entriesToGet' : IDL.Nat,
});
export const GetMoodEntries = IDL.Record({
  'skip' : IDL.Nat,
  'moodTags' : IDL.Vec(IDL.Text),
  'timeRange' : IDL.Variant({
    'all' : IDL.Null,
    'entriesBefore' : Timestamp,
    'entriesAfter' : Timestamp,
    'entriesBetween' : IDL.Tuple(Timestamp, Timestamp),
  }),
  'entriesToGet' : IDL.Nat,
});
export const DayAnalysis = IDL.Record({
  'calories' : IDL.Float64,
  'omega3' : IDL.Float64,
  'magnesium' : IDL.Float64,
  'moodScore' : IDL.Float64,
  'recommendation' : IDL.Text,
});
export const PersonalizedInsights = IDL.Record({
  'recommendations' : IDL.Text,
  'dayAnalysis' : IDL.Vec(DayAnalysis),
});
export const SuperUserStatus = IDL.Record({
  'userRole' : UserRole,
  'userStatus' : IDL.Variant({
    'inactive' : IDL.Null,
    'userStatus' : UserStatus,
  }),
});
export const UserSummary = IDL.Record({
  'status' : UserStatus,
  'lastActivity' : IDL.Opt(Timestamp),
  'riskFlag' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOnboarding' : IDL.Func([UserProfile], [], []),
  'getAggregateAnalytics' : IDL.Func([], [AggregateAnalytics], ['query']),
  'getAllCurrentUserFoodEntriesReverse' : IDL.Func(
      [],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getAllCurrentUserMoodEntries' : IDL.Func(
      [],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getAllCurrentUserMoodEntriesReverse' : IDL.Func(
      [],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getAllFoodEntriesForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getAllFoodEntriesForCurrentUserByFoodNames' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getAllFoodEntriesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAverageMoodScore' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserFoodEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FoodEntry)],
      ['query'],
    ),
  'getCurrentUserMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getCurrentUserMoodEntryIdsByMoodTags' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCurrentUsersWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStatus))],
      ['query'],
    ),
  'getFoodEntries' : IDL.Func(
      [GetFoodEntriesFrom],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getFoodEntriesAfterTime' : IDL.Func(
      [IDL.Record({ 'afterTime' : Timestamp }), IDL.Principal],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getFoodEntriesAfterTimeForUser' : IDL.Func(
      [Timestamp, IDL.Principal],
      [IDL.Vec(FoodEntry)],
      [],
    ),
  'getFoodEntriesForCurrentUser' : IDL.Func(
      [GetFoodEntriesRequest],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getFoodEntriesIdsWithImageForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getFoodEntriesWithImageForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getFoodEntryById' : IDL.Func([IDL.Text], [IDL.Opt(FoodEntry)], ['query']),
  'getFoodEntryIdsForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getFoodEntryIdsForCurrentUserByFoodNames' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getFoodEntryImage' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'getHighestOmega3FoodEntriesForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'getMoodEntriesForCurrentUser' : IDL.Func(
      [GetMoodEntries],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getMoodEntriesForUser' : IDL.Func(
      [GetMoodEntries, IDL.Principal],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getMoodEntriesIdForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getMoodEntriesIdsForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getMoodEntriesIdsForUserByMoodTags' : IDL.Func(
      [IDL.Principal, IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getMoodEntryIdsForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPersonalizedInsights' : IDL.Func([], [PersonalizedInsights], ['query']),
  'getSuperUserStatus' : IDL.Func(
      [IDL.Principal],
      [SuperUserStatus],
      ['query'],
    ),
  'getUserMoodEntryWithId' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [MoodEntry],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [UserProfile],
      ['query'],
    ),
  'getUserStatus' : IDL.Func([IDL.Principal], [UserStatus], ['query']),
  'getUsersWithStatus' : IDL.Func(
      [UserStatus],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getUsersWithStatusSummary' : IDL.Func(
      [UserStatus],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserSummary))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'logFoodEntry' : IDL.Func([FoodEntry], [], []),
  'logMoodEntry' : IDL.Func([MoodEntry], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'searchFoodEntries' : IDL.Func(
      [IDL.Record({ 'foodNames' : IDL.Vec(IDL.Text) })],
      [IDL.Vec(FoodEntry)],
      ['query'],
    ),
  'searchMoodEntries' : IDL.Func(
      [IDL.Record({ 'moodTags' : IDL.Vec(IDL.Text) })],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'searchUserProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setFoodEntryImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'setStatusToUserForAdmin' : IDL.Func([IDL.Principal, UserStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'userId' : IDL.Text,
    'goals' : IDL.Text,
    'gender' : IDL.Text,
    'healthConditions' : IDL.Vec(IDL.Text),
    'dietType' : IDL.Text,
  });
  const AggregateAnalytics = IDL.Record({
    'activeUsers' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'nutrientTrends' : IDL.Text,
    'averageMoodScore' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FoodEntry = IDL.Record({
    'id' : IDL.Text,
    'calories' : IDL.Float64,
    'time' : Timestamp,
    'omega3' : IDL.Float64,
    'magnesium' : IDL.Float64,
    'image' : IDL.Opt(ExternalBlob),
    'foodName' : IDL.Text,
  });
  const MoodEntry = IDL.Record({
    'id' : IDL.Text,
    'time' : Timestamp,
    'score' : IDL.Float64,
    'moodTags' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'restricted' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const GetFoodEntriesFrom = IDL.Record({
    'foodNames' : IDL.Vec(IDL.Text),
    'skip' : IDL.Nat,
    'timeRange' : IDL.Variant({
      'all' : IDL.Null,
      'entriesBefore' : Timestamp,
      'entriesAfter' : Timestamp,
      'entriesBetween' : IDL.Tuple(Timestamp, Timestamp),
    }),
    'fromUser' : IDL.Principal,
    'entriesToGet' : IDL.Nat,
  });
  const GetFoodEntriesRequest = IDL.Record({
    'foodNames' : IDL.Vec(IDL.Text),
    'skip' : IDL.Nat,
    'timeRange' : IDL.Variant({
      'all' : IDL.Null,
      'entriesBefore' : Timestamp,
      'entriesAfter' : Timestamp,
      'entriesBetween' : IDL.Tuple(Timestamp, Timestamp),
    }),
    'entriesToGet' : IDL.Nat,
  });
  const GetMoodEntries = IDL.Record({
    'skip' : IDL.Nat,
    'moodTags' : IDL.Vec(IDL.Text),
    'timeRange' : IDL.Variant({
      'all' : IDL.Null,
      'entriesBefore' : Timestamp,
      'entriesAfter' : Timestamp,
      'entriesBetween' : IDL.Tuple(Timestamp, Timestamp),
    }),
    'entriesToGet' : IDL.Nat,
  });
  const DayAnalysis = IDL.Record({
    'calories' : IDL.Float64,
    'omega3' : IDL.Float64,
    'magnesium' : IDL.Float64,
    'moodScore' : IDL.Float64,
    'recommendation' : IDL.Text,
  });
  const PersonalizedInsights = IDL.Record({
    'recommendations' : IDL.Text,
    'dayAnalysis' : IDL.Vec(DayAnalysis),
  });
  const SuperUserStatus = IDL.Record({
    'userRole' : UserRole,
    'userStatus' : IDL.Variant({
      'inactive' : IDL.Null,
      'userStatus' : UserStatus,
    }),
  });
  const UserSummary = IDL.Record({
    'status' : UserStatus,
    'lastActivity' : IDL.Opt(Timestamp),
    'riskFlag' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOnboarding' : IDL.Func([UserProfile], [], []),
    'getAggregateAnalytics' : IDL.Func([], [AggregateAnalytics], ['query']),
    'getAllCurrentUserFoodEntriesReverse' : IDL.Func(
        [],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getAllCurrentUserMoodEntries' : IDL.Func(
        [],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getAllCurrentUserMoodEntriesReverse' : IDL.Func(
        [],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getAllFoodEntriesForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getAllFoodEntriesForCurrentUserByFoodNames' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getAllFoodEntriesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAverageMoodScore' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserFoodEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FoodEntry)],
        ['query'],
      ),
    'getCurrentUserMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getCurrentUserMoodEntryIdsByMoodTags' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCurrentUsersWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStatus))],
        ['query'],
      ),
    'getFoodEntries' : IDL.Func(
        [GetFoodEntriesFrom],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getFoodEntriesAfterTime' : IDL.Func(
        [IDL.Record({ 'afterTime' : Timestamp }), IDL.Principal],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getFoodEntriesAfterTimeForUser' : IDL.Func(
        [Timestamp, IDL.Principal],
        [IDL.Vec(FoodEntry)],
        [],
      ),
    'getFoodEntriesForCurrentUser' : IDL.Func(
        [GetFoodEntriesRequest],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getFoodEntriesIdsWithImageForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getFoodEntriesWithImageForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getFoodEntryById' : IDL.Func([IDL.Text], [IDL.Opt(FoodEntry)], ['query']),
    'getFoodEntryIdsForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getFoodEntryIdsForCurrentUserByFoodNames' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getFoodEntryImage' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'getHighestOmega3FoodEntriesForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'getMoodEntriesForCurrentUser' : IDL.Func(
        [GetMoodEntries],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getMoodEntriesForUser' : IDL.Func(
        [GetMoodEntries, IDL.Principal],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getMoodEntriesIdForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getMoodEntriesIdsForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getMoodEntriesIdsForUserByMoodTags' : IDL.Func(
        [IDL.Principal, IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getMoodEntryIdsForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPersonalizedInsights' : IDL.Func([], [PersonalizedInsights], ['query']),
    'getSuperUserStatus' : IDL.Func(
        [IDL.Principal],
        [SuperUserStatus],
        ['query'],
      ),
    'getUserMoodEntryWithId' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [MoodEntry],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [UserProfile],
        ['query'],
      ),
    'getUserStatus' : IDL.Func([IDL.Principal], [UserStatus], ['query']),
    'getUsersWithStatus' : IDL.Func(
        [UserStatus],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getUsersWithStatusSummary' : IDL.Func(
        [UserStatus],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserSummary))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'logFoodEntry' : IDL.Func([FoodEntry], [], []),
    'logMoodEntry' : IDL.Func([MoodEntry], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'searchFoodEntries' : IDL.Func(
        [IDL.Record({ 'foodNames' : IDL.Vec(IDL.Text) })],
        [IDL.Vec(FoodEntry)],
        ['query'],
      ),
    'searchMoodEntries' : IDL.Func(
        [IDL.Record({ 'moodTags' : IDL.Vec(IDL.Text) })],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'searchUserProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setFoodEntryImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'setStatusToUserForAdmin' : IDL.Func([IDL.Principal, UserStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };