/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AggregateAnalytics {
  'activeUsers' : bigint,
  'totalUsers' : bigint,
  'nutrientTrends' : string,
  'averageMoodScore' : number,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DayAnalysis {
  'calories' : number,
  'omega3' : number,
  'magnesium' : number,
  'moodScore' : number,
  'recommendation' : string,
}
export type ExternalBlob = Uint8Array;
export interface FoodEntry {
  'id' : string,
  'calories' : number,
  'time' : Timestamp,
  'omega3' : number,
  'magnesium' : number,
  'image' : [] | [ExternalBlob],
  'foodName' : string,
}
export interface GetFoodEntriesFrom {
  'foodNames' : Array<string>,
  'skip' : bigint,
  'timeRange' : { 'all' : null } |
    { 'entriesBefore' : Timestamp } |
    { 'entriesAfter' : Timestamp } |
    { 'entriesBetween' : [Timestamp, Timestamp] },
  'fromUser' : Principal,
  'entriesToGet' : bigint,
}
export interface GetFoodEntriesRequest {
  'foodNames' : Array<string>,
  'skip' : bigint,
  'timeRange' : { 'all' : null } |
    { 'entriesBefore' : Timestamp } |
    { 'entriesAfter' : Timestamp } |
    { 'entriesBetween' : [Timestamp, Timestamp] },
  'entriesToGet' : bigint,
}
export interface GetMoodEntries {
  'skip' : bigint,
  'moodTags' : Array<string>,
  'timeRange' : { 'all' : null } |
    { 'entriesBefore' : Timestamp } |
    { 'entriesAfter' : Timestamp } |
    { 'entriesBetween' : [Timestamp, Timestamp] },
  'entriesToGet' : bigint,
}
export interface MoodEntry {
  'id' : string,
  'time' : Timestamp,
  'score' : number,
  'moodTags' : Array<string>,
  'notes' : string,
}
export interface PersonalizedInsights {
  'recommendations' : string,
  'dayAnalysis' : Array<DayAnalysis>,
}
export interface SuperUserStatus {
  'userRole' : UserRole,
  'userStatus' : { 'inactive' : null } |
    { 'userStatus' : UserStatus },
}
export type Timestamp = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'age' : bigint,
  'userId' : string,
  'goals' : string,
  'gender' : string,
  'healthConditions' : Array<string>,
  'dietType' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'restricted' : null } |
  { 'suspended' : null };
export interface UserSummary {
  'status' : UserStatus,
  'lastActivity' : [] | [Timestamp],
  'riskFlag' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOnboarding' : ActorMethod<[UserProfile], undefined>,
  'getAggregateAnalytics' : ActorMethod<[], AggregateAnalytics>,
  'getAllCurrentUserFoodEntriesReverse' : ActorMethod<[], Array<FoodEntry>>,
  'getAllCurrentUserMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'getAllCurrentUserMoodEntriesReverse' : ActorMethod<[], Array<MoodEntry>>,
  'getAllFoodEntriesForCurrentUser' : ActorMethod<[], Array<FoodEntry>>,
  'getAllFoodEntriesForCurrentUserByFoodNames' : ActorMethod<
    [Array<string>],
    Array<FoodEntry>
  >,
  'getAllFoodEntriesForUser' : ActorMethod<[Principal], Array<FoodEntry>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAverageMoodScore' : ActorMethod<[], number>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserFoodEntry' : ActorMethod<[string], [] | [FoodEntry]>,
  'getCurrentUserMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'getCurrentUserMoodEntryIdsByMoodTags' : ActorMethod<
    [Array<string>],
    Array<string>
  >,
  'getCurrentUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCurrentUsersWithStatus' : ActorMethod<[], Array<[Principal, UserStatus]>>,
  'getFoodEntries' : ActorMethod<[GetFoodEntriesFrom], Array<FoodEntry>>,
  'getFoodEntriesAfterTime' : ActorMethod<
    [{ 'afterTime' : Timestamp }, Principal],
    Array<FoodEntry>
  >,
  'getFoodEntriesAfterTimeForUser' : ActorMethod<
    [Timestamp, Principal],
    Array<FoodEntry>
  >,
  'getFoodEntriesForCurrentUser' : ActorMethod<
    [GetFoodEntriesRequest],
    Array<FoodEntry>
  >,
  'getFoodEntriesIdsWithImageForCurrentUser' : ActorMethod<[], Array<string>>,
  'getFoodEntriesWithImageForCurrentUser' : ActorMethod<[], Array<FoodEntry>>,
  'getFoodEntryById' : ActorMethod<[string], [] | [FoodEntry]>,
  'getFoodEntryIdsForCurrentUser' : ActorMethod<[], Array<string>>,
  'getFoodEntryIdsForCurrentUserByFoodNames' : ActorMethod<
    [Array<string>],
    Array<string>
  >,
  'getFoodEntryImage' : ActorMethod<[string], ExternalBlob>,
  'getHighestOmega3FoodEntriesForCurrentUser' : ActorMethod<
    [],
    Array<FoodEntry>
  >,
  'getMoodEntriesForCurrentUser' : ActorMethod<
    [GetMoodEntries],
    Array<MoodEntry>
  >,
  'getMoodEntriesForUser' : ActorMethod<
    [GetMoodEntries, Principal],
    Array<MoodEntry>
  >,
  'getMoodEntriesIdForUser' : ActorMethod<[Principal], Array<string>>,
  'getMoodEntriesIdsForCurrentUser' : ActorMethod<[], Array<string>>,
  'getMoodEntriesIdsForUserByMoodTags' : ActorMethod<
    [Principal, Array<string>],
    Array<string>
  >,
  'getMoodEntryIdsForCurrentUser' : ActorMethod<[], Array<string>>,
  'getPersonalizedInsights' : ActorMethod<[], PersonalizedInsights>,
  'getSuperUserStatus' : ActorMethod<[Principal], SuperUserStatus>,
  'getUserMoodEntryWithId' : ActorMethod<[string, Principal], MoodEntry>,
  'getUserProfile' : ActorMethod<[string], UserProfile>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], UserProfile>,
  'getUserStatus' : ActorMethod<[Principal], UserStatus>,
  'getUsersWithStatus' : ActorMethod<[UserStatus], Array<Principal>>,
  'getUsersWithStatusSummary' : ActorMethod<
    [UserStatus],
    Array<[Principal, UserSummary]>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'logFoodEntry' : ActorMethod<[FoodEntry], undefined>,
  'logMoodEntry' : ActorMethod<[MoodEntry], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'searchFoodEntries' : ActorMethod<
    [{ 'foodNames' : Array<string> }],
    Array<FoodEntry>
  >,
  'searchMoodEntries' : ActorMethod<
    [{ 'moodTags' : Array<string> }],
    Array<MoodEntry>
  >,
  'searchUserProfiles' : ActorMethod<[string], Array<UserProfile>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setFoodEntryImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'setStatusToUserForAdmin' : ActorMethod<[Principal, UserStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];