/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GetFoodEntriesFrom {
    foodNames: Array<string>;
    skip: bigint;
    timeRange: {
        __kind__: "all";
        all: null;
    } | {
        __kind__: "entriesBefore";
        entriesBefore: Timestamp;
    } | {
        __kind__: "entriesAfter";
        entriesAfter: Timestamp;
    } | {
        __kind__: "entriesBetween";
        entriesBetween: [Timestamp, Timestamp];
    };
    fromUser: Principal;
    entriesToGet: bigint;
}
export interface DayAnalysis {
    calories: number;
    omega3: number;
    magnesium: number;
    moodScore: number;
    recommendation: string;
}
export type Timestamp = bigint;
export interface SuperUserStatus {
    userRole: UserRole;
    userStatus: {
        __kind__: "inactive";
        inactive: null;
    } | {
        __kind__: "userStatus";
        userStatus: UserStatus;
    };
}
export interface PersonalizedInsights {
    recommendations: string;
    dayAnalysis: Array<DayAnalysis>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MoodEntry {
    id: string;
    time: Timestamp;
    score: number;
    moodTags: Array<string>;
    notes: string;
}
export interface GetFoodEntriesRequest {
    foodNames: Array<string>;
    skip: bigint;
    timeRange: {
        __kind__: "all";
        all: null;
    } | {
        __kind__: "entriesBefore";
        entriesBefore: Timestamp;
    } | {
        __kind__: "entriesAfter";
        entriesAfter: Timestamp;
    } | {
        __kind__: "entriesBetween";
        entriesBetween: [Timestamp, Timestamp];
    };
    entriesToGet: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface FoodEntry {
    id: string;
    calories: number;
    time: Timestamp;
    omega3: number;
    magnesium: number;
    image?: ExternalBlob;
    foodName: string;
}
export interface AggregateAnalytics {
    activeUsers: bigint;
    totalUsers: bigint;
    nutrientTrends: string;
    averageMoodScore: number;
}
export interface UserSummary {
    status: UserStatus;
    lastActivity?: Timestamp;
    riskFlag: string;
}
export interface GetMoodEntries {
    skip: bigint;
    moodTags: Array<string>;
    timeRange: {
        __kind__: "all";
        all: null;
    } | {
        __kind__: "entriesBefore";
        entriesBefore: Timestamp;
    } | {
        __kind__: "entriesAfter";
        entriesAfter: Timestamp;
    } | {
        __kind__: "entriesBetween";
        entriesBetween: [Timestamp, Timestamp];
    };
    entriesToGet: bigint;
}
export interface UserProfile {
    age: bigint;
    userId: string;
    goals: string;
    gender: string;
    healthConditions: Array<string>;
    dietType: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    restricted = "restricted",
    suspended = "suspended"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeOnboarding(profile: UserProfile): Promise<void>;
    getAggregateAnalytics(): Promise<AggregateAnalytics>;
    getAllCurrentUserFoodEntriesReverse(): Promise<Array<FoodEntry>>;
    getAllCurrentUserMoodEntries(): Promise<Array<MoodEntry>>;
    getAllCurrentUserMoodEntriesReverse(): Promise<Array<MoodEntry>>;
    getAllFoodEntriesForCurrentUser(): Promise<Array<FoodEntry>>;
    getAllFoodEntriesForCurrentUserByFoodNames(foodNames: Array<string>): Promise<Array<FoodEntry>>;
    getAllFoodEntriesForUser(user: Principal): Promise<Array<FoodEntry>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAverageMoodScore(): Promise<number>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUserFoodEntry(id: string): Promise<FoodEntry | null>;
    getCurrentUserMoodEntries(): Promise<Array<MoodEntry>>;
    getCurrentUserMoodEntryIdsByMoodTags(moodTags: Array<string>): Promise<Array<string>>;
    getCurrentUserProfile(): Promise<UserProfile | null>;
    getCurrentUsersWithStatus(): Promise<Array<[Principal, UserStatus]>>;
    getFoodEntries(request: GetFoodEntriesFrom): Promise<Array<FoodEntry>>;
    getFoodEntriesAfterTime(request: {
        afterTime: Timestamp;
    }, principal: Principal): Promise<Array<FoodEntry>>;
    getFoodEntriesAfterTimeForUser(time: Timestamp, user: Principal): Promise<Array<FoodEntry>>;
    getFoodEntriesForCurrentUser(request: GetFoodEntriesRequest): Promise<Array<FoodEntry>>;
    getFoodEntriesIdsWithImageForCurrentUser(): Promise<Array<string>>;
    getFoodEntriesWithImageForCurrentUser(): Promise<Array<FoodEntry>>;
    getFoodEntryById(id: string): Promise<FoodEntry | null>;
    getFoodEntryIdsForCurrentUser(): Promise<Array<string>>;
    getFoodEntryIdsForCurrentUserByFoodNames(foodNames: Array<string>): Promise<Array<string>>;
    getFoodEntryImage(foodEntryId: string): Promise<ExternalBlob>;
    getHighestOmega3FoodEntriesForCurrentUser(): Promise<Array<FoodEntry>>;
    getMoodEntriesForCurrentUser(request: GetMoodEntries): Promise<Array<MoodEntry>>;
    getMoodEntriesForUser(request: GetMoodEntries, user: Principal): Promise<Array<MoodEntry>>;
    getMoodEntriesIdForUser(user: Principal): Promise<Array<string>>;
    getMoodEntriesIdsForCurrentUser(): Promise<Array<string>>;
    getMoodEntriesIdsForUserByMoodTags(user: Principal, moodTags: Array<string>): Promise<Array<string>>;
    getMoodEntryIdsForCurrentUser(): Promise<Array<string>>;
    getPersonalizedInsights(): Promise<PersonalizedInsights>;
    getSuperUserStatus(user: Principal): Promise<SuperUserStatus>;
    getUserMoodEntryWithId(id: string, user: Principal): Promise<MoodEntry>;
    getUserProfile(userId: string): Promise<UserProfile>;
    getUserProfileByPrincipal(user: Principal): Promise<UserProfile>;
    getUserStatus(user: Principal): Promise<UserStatus>;
    getUsersWithStatus(status: UserStatus): Promise<Array<Principal>>;
    getUsersWithStatusSummary(status: UserStatus): Promise<Array<[Principal, UserSummary]>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    logFoodEntry(foodEntry: FoodEntry): Promise<void>;
    logMoodEntry(moodEntry: MoodEntry): Promise<void>;
    requestApproval(): Promise<void>;
    searchFoodEntries(arg0: {
        foodNames: Array<string>;
    }): Promise<Array<FoodEntry>>;
    searchMoodEntries(arg0: {
        moodTags: Array<string>;
    }): Promise<Array<MoodEntry>>;
    searchUserProfiles(searchText: string): Promise<Array<UserProfile>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setFoodEntryImage(foodEntryId: string, image: ExternalBlob): Promise<void>;
    setStatusToUserForAdmin(user: Principal, status: UserStatus): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, ExternalBlob as _ExternalBlob, FoodEntry as _FoodEntry, GetFoodEntriesFrom as _GetFoodEntriesFrom, GetFoodEntriesRequest as _GetFoodEntriesRequest, GetMoodEntries as _GetMoodEntries, SuperUserStatus as _SuperUserStatus, Timestamp as _Timestamp, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, UserStatus as _UserStatus, UserSummary as _UserSummary, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeOnboarding(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding(arg0);
            return result;
        }
    }
    async getAggregateAnalytics(): Promise<AggregateAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregateAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregateAnalytics();
            return result;
        }
    }
    async getAllCurrentUserFoodEntriesReverse(): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCurrentUserFoodEntriesReverse();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCurrentUserFoodEntriesReverse();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCurrentUserMoodEntries(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCurrentUserMoodEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCurrentUserMoodEntries();
            return result;
        }
    }
    async getAllCurrentUserMoodEntriesReverse(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCurrentUserMoodEntriesReverse();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCurrentUserMoodEntriesReverse();
            return result;
        }
    }
    async getAllFoodEntriesForCurrentUser(): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodEntriesForCurrentUser();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodEntriesForCurrentUser();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFoodEntriesForCurrentUserByFoodNames(arg0: Array<string>): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodEntriesForCurrentUserByFoodNames(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodEntriesForCurrentUserByFoodNames(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFoodEntriesForUser(arg0: Principal): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodEntriesForUser(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodEntriesForUser(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getAverageMoodScore(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageMoodScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageMoodScore();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserFoodEntry(arg0: string): Promise<FoodEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserFoodEntry(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserFoodEntry(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserMoodEntries(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserMoodEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserMoodEntries();
            return result;
        }
    }
    async getCurrentUserMoodEntryIdsByMoodTags(arg0: Array<string>): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserMoodEntryIdsByMoodTags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserMoodEntryIdsByMoodTags(arg0);
            return result;
        }
    }
    async getCurrentUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUsersWithStatus(): Promise<Array<[Principal, UserStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUsersWithStatus();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUsersWithStatus();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntries(arg0: GetFoodEntriesFrom): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntries(to_candid_GetFoodEntriesFrom_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntries(to_candid_GetFoodEntriesFrom_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntriesAfterTime(arg0: {
        afterTime: Timestamp;
    }, arg1: Principal): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntriesAfterTime(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntriesAfterTime(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntriesAfterTimeForUser(arg0: Timestamp, arg1: Principal): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntriesAfterTimeForUser(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntriesAfterTimeForUser(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntriesForCurrentUser(arg0: GetFoodEntriesRequest): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntriesForCurrentUser(to_candid_GetFoodEntriesRequest_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntriesForCurrentUser(to_candid_GetFoodEntriesRequest_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntriesIdsWithImageForCurrentUser(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntriesIdsWithImageForCurrentUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntriesIdsWithImageForCurrentUser();
            return result;
        }
    }
    async getFoodEntriesWithImageForCurrentUser(): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntriesWithImageForCurrentUser();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntriesWithImageForCurrentUser();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntryById(arg0: string): Promise<FoodEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntryById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntryById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodEntryIdsForCurrentUser(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntryIdsForCurrentUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntryIdsForCurrentUser();
            return result;
        }
    }
    async getFoodEntryIdsForCurrentUserByFoodNames(arg0: Array<string>): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntryIdsForCurrentUserByFoodNames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntryIdsForCurrentUserByFoodNames(arg0);
            return result;
        }
    }
    async getFoodEntryImage(arg0: string): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodEntryImage(arg0);
                return from_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodEntryImage(arg0);
            return from_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHighestOmega3FoodEntriesForCurrentUser(): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighestOmega3FoodEntriesForCurrentUser();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighestOmega3FoodEntriesForCurrentUser();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoodEntriesForCurrentUser(arg0: GetMoodEntries): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesForCurrentUser(to_candid_GetMoodEntries_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesForCurrentUser(to_candid_GetMoodEntries_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMoodEntriesForUser(arg0: GetMoodEntries, arg1: Principal): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesForUser(to_candid_GetMoodEntries_n28(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesForUser(to_candid_GetMoodEntries_n28(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getMoodEntriesIdForUser(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesIdForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesIdForUser(arg0);
            return result;
        }
    }
    async getMoodEntriesIdsForCurrentUser(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesIdsForCurrentUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesIdsForCurrentUser();
            return result;
        }
    }
    async getMoodEntriesIdsForUserByMoodTags(arg0: Principal, arg1: Array<string>): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntriesIdsForUserByMoodTags(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntriesIdsForUserByMoodTags(arg0, arg1);
            return result;
        }
    }
    async getMoodEntryIdsForCurrentUser(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntryIdsForCurrentUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntryIdsForCurrentUser();
            return result;
        }
    }
    async getPersonalizedInsights(): Promise<PersonalizedInsights> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalizedInsights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalizedInsights();
            return result;
        }
    }
    async getSuperUserStatus(arg0: Principal): Promise<SuperUserStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuperUserStatus(arg0);
                return from_candid_SuperUserStatus_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuperUserStatus(arg0);
            return from_candid_SuperUserStatus_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMoodEntryWithId(arg0: string, arg1: Principal): Promise<MoodEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMoodEntryWithId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMoodEntryWithId(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return result;
        }
    }
    async getUserProfileByPrincipal(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByPrincipal(arg0);
            return result;
        }
    }
    async getUserStatus(arg0: Principal): Promise<UserStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatus(arg0);
                return from_candid_UserStatus_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatus(arg0);
            return from_candid_UserStatus_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersWithStatus(arg0: UserStatus): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersWithStatus(to_candid_UserStatus_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersWithStatus(to_candid_UserStatus_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUsersWithStatusSummary(arg0: UserStatus): Promise<Array<[Principal, UserSummary]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersWithStatusSummary(to_candid_UserStatus_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersWithStatusSummary(to_candid_UserStatus_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async logFoodEntry(arg0: FoodEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logFoodEntry(await to_candid_FoodEntry_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFoodEntry(await to_candid_FoodEntry_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async logMoodEntry(arg0: MoodEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMoodEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMoodEntry(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async searchFoodEntries(arg0: {
        foodNames: Array<string>;
    }): Promise<Array<FoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoodEntries(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoodEntries(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchMoodEntries(arg0: {
        moodTags: Array<string>;
    }): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMoodEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMoodEntries(arg0);
            return result;
        }
    }
    async searchUserProfiles(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUserProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUserProfiles(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setFoodEntryImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFoodEntryImage(arg0, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFoodEntryImage(arg0, await to_candid_ExternalBlob_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStatusToUserForAdmin(arg0: Principal, arg1: UserStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStatusToUserForAdmin(arg0, to_candid_UserStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStatusToUserForAdmin(arg0, to_candid_UserStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FoodEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodEntry): Promise<FoodEntry> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SuperUserStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuperUserStatus): SuperUserStatus {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserSummary_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodEntry]): Promise<FoodEntry | null> {
    return value.length === 0 ? null : await from_candid_FoodEntry_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    calories: number;
    time: _Timestamp;
    omega3: number;
    magnesium: number;
    image: [] | [_ExternalBlob];
    foodName: string;
}): Promise<{
    id: string;
    calories: number;
    time: Timestamp;
    omega3: number;
    magnesium: number;
    image?: ExternalBlob;
    foodName: string;
}> {
    return {
        id: value.id,
        calories: value.calories,
        time: value.time,
        omega3: value.omega3,
        magnesium: value.magnesium,
        image: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.image)),
        foodName: value.foodName
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userRole: _UserRole;
    userStatus: {
        inactive: null;
    } | {
        userStatus: _UserStatus;
    };
}): {
    userRole: UserRole;
    userStatus: {
        __kind__: "inactive";
        inactive: null;
    } | {
        __kind__: "userStatus";
        userStatus: UserStatus;
    };
} {
    return {
        userRole: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.userRole),
        userStatus: from_candid_variant_n32(_uploadFile, _downloadFile, value.userStatus)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    lastActivity: [] | [_Timestamp];
    riskFlag: string;
}): {
    status: UserStatus;
    lastActivity?: Timestamp;
    riskFlag: string;
} {
    return {
        status: from_candid_UserStatus_n21(_uploadFile, _downloadFile, value.status),
        lastActivity: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.lastActivity)),
        riskFlag: value.riskFlag
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n43(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserStatus]): [Principal, UserStatus] {
    return [
        value[0],
        from_candid_UserStatus_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserSummary]): [Principal, UserSummary] {
    return [
        value[0],
        from_candid_UserSummary_n37(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    restricted: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "restricted" in value ? UserStatus.restricted : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inactive: null;
} | {
    userStatus: _UserStatus;
}): {
    __kind__: "inactive";
    inactive: null;
} | {
    __kind__: "userStatus";
    userStatus: UserStatus;
} {
    return "inactive" in value ? {
        __kind__: "inactive",
        inactive: value.inactive
    } : "userStatus" in value ? {
        __kind__: "userStatus",
        userStatus: from_candid_UserStatus_n21(_uploadFile, _downloadFile, value.userStatus)
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodEntry>): Promise<Array<FoodEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FoodEntry_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserStatus]>): Array<[Principal, UserStatus]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserSummary]>): Array<[Principal, UserSummary]> {
    return value.map((x)=>from_candid_tuple_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n41(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FoodEntry_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodEntry): Promise<_FoodEntry> {
    return await to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_GetFoodEntriesFrom_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GetFoodEntriesFrom): _GetFoodEntriesFrom {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_GetFoodEntriesRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GetFoodEntriesRequest): _GetFoodEntriesRequest {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_GetMoodEntries_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GetMoodEntries): _GetMoodEntries {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    foodNames: Array<string>;
    skip: bigint;
    timeRange: {
        __kind__: "all";
        all: null;
    } | {
        __kind__: "entriesBefore";
        entriesBefore: Timestamp;
    } | {
        __kind__: "entriesAfter";
        entriesAfter: Timestamp;
    } | {
        __kind__: "entriesBetween";
        entriesBetween: [Timestamp, Timestamp];
    };
    fromUser: Principal;
    entriesToGet: bigint;
}): {
    foodNames: Array<string>;
    skip: bigint;
    timeRange: {
        all: null;
    } | {
        entriesBefore: _Timestamp;
    } | {
        entriesAfter: _Timestamp;
    } | {
        entriesBetween: [_Timestamp, _Timestamp];
    };
    fromUser: Principal;
    entriesToGet: bigint;
} {
    return {
        foodNames: value.foodNames,
        skip: value.skip,
        timeRange: to_candid_variant_n25(_uploadFile, _downloadFile, value.timeRange),
        fromUser: value.fromUser,
        entriesToGet: value.entriesToGet
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    foodNames: Array<string>;
    skip: bigint;
    timeRange: {
        __kind__: "all";
        all: null;
    } | {
        __kind__: "entriesBefore";
        entriesBefore: Timestamp;
    } | {
        __kind__: "entriesAfter";
        entriesAfter: Timestamp;
    } | {
        __kind__: "entriesBetween";
        entriesBetween: [Timestamp, Timestamp];
    };
    entriesToGet: bigint;
}): {
    foodNames: Array<string>;
    skip: bigint;
    timeRange: {
        all: null;
    } | {
        entriesBefore: _Timestamp;
    } | {
        entriesAfter: _Timestamp;
    } | {
        entriesBetween: [_Timestamp, _Timestamp];
    };
    entriesToGet: bigint;
} {
    return {
        foodNames: value.foodNames,
        skip: value.skip,
        timeRange: to_candid_variant_n25(_uploadFile, _downloadFile, value.timeRange),
        entriesToGet: value.entriesToGet
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skip: bigint;
    moodTags: Array<string>;
    timeRange: {
        __kind__: "all";
        all: null;
    } | {
        __kind__: "entriesBefore";
        entriesBefore: Timestamp;
    } | {
        __kind__: "entriesAfter";
        entriesAfter: Timestamp;
    } | {
        __kind__: "entriesBetween";
        entriesBetween: [Timestamp, Timestamp];
    };
    entriesToGet: bigint;
}): {
    skip: bigint;
    moodTags: Array<string>;
    timeRange: {
        all: null;
    } | {
        entriesBefore: _Timestamp;
    } | {
        entriesAfter: _Timestamp;
    } | {
        entriesBetween: [_Timestamp, _Timestamp];
    };
    entriesToGet: bigint;
} {
    return {
        skip: value.skip,
        moodTags: value.moodTags,
        timeRange: to_candid_variant_n25(_uploadFile, _downloadFile, value.timeRange),
        entriesToGet: value.entriesToGet
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    calories: number;
    time: Timestamp;
    omega3: number;
    magnesium: number;
    image?: ExternalBlob;
    foodName: string;
}): Promise<{
    id: string;
    calories: number;
    time: _Timestamp;
    omega3: number;
    magnesium: number;
    image: [] | [_ExternalBlob];
    foodName: string;
}> {
    return {
        id: value.id,
        calories: value.calories,
        time: value.time,
        omega3: value.omega3,
        magnesium: value.magnesium,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n47(_uploadFile, _downloadFile, value.image)) : candid_none(),
        foodName: value.foodName
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "all";
    all: null;
} | {
    __kind__: "entriesBefore";
    entriesBefore: Timestamp;
} | {
    __kind__: "entriesAfter";
    entriesAfter: Timestamp;
} | {
    __kind__: "entriesBetween";
    entriesBetween: [Timestamp, Timestamp];
}): {
    all: null;
} | {
    entriesBefore: _Timestamp;
} | {
    entriesAfter: _Timestamp;
} | {
    entriesBetween: [_Timestamp, _Timestamp];
} {
    return value.__kind__ === "all" ? {
        all: value.all
    } : value.__kind__ === "entriesBefore" ? {
        entriesBefore: value.entriesBefore
    } : value.__kind__ === "entriesAfter" ? {
        entriesAfter: value.entriesAfter
    } : value.__kind__ === "entriesBetween" ? {
        entriesBetween: value.entriesBetween
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    restricted: null;
} | {
    suspended: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.restricted ? {
        restricted: null
    } : value == UserStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
